version: "3"
services:
  api:
    build:
      context: .
      dockerfile: ./dockerfile.api
    ports:
      - "8000:8000"

  web:
    build:
      context: .
      dockerfile: ./dockerfile.web

  nginx:
    image: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
      - web